const lista = [
  {
    nombre: "Gaspar",
    apellido: "De Carlo",
    experienciaJs: true,
    experienciaVersionado: true,
    dni: 29502368,
  },
  {
    nombre: "Matias",
    apellido: "Alvarez",
    experienciaJs: true,
    experienciaVersionado: true,
    dni: 99999999,
  },
  {
    nombre: "Terrens",
    apellido: "Javier",
    experienciaJs: true,
    experienciaVersionado: true,
    dni: 33257631,
  },
  {
    nombre: "Ezequiel",
    apellido: "Ilivitzky",
    experienciaJs: true,
    experienciaVersionado: true,
    dni: 34538783,
  },
  {
    nombre: "Celina",
    apellido: "Rinaldi",
    experienciaJs: true,
    experienciaVersionado: true,
    dni: 44110736,
  },
  {
    nombre: "Javier",
    apellido: "Toso",
    experienciaJs: true,
    experienciaVersionado: true,
    dni: 39212040,
  },
  {
    nombre: "Sergio",
    apellido: "Chocobar",
    experienciaJs: true,
    experienciaVersionado: true,
    dni: 38087951,
  },

  {
    nombre: "Iván",
    apellido: "Laborde",
    experienciaJs: false,
    experienciaVersionado: false,
    dni: 42470327,
  },
  {
    nombre: "David",
    apellido: "Nobati",
    experienciaJs: true,
    experienciaVersionado: false,
    dni: 43872165,
  },
  {
    nombre: "Brian",
    apellido: "Sfintzi",
    experienciaJs: false,
    experienciaVersionado: false,
    dni: 39457408,
  },
  {
    nombre: "Nicolas",
    apellido: "Zapata",
    experienciaJs: false,
    experienciaVersionado: false,
    dni: 39212358,
  },
  {
    nombre: "Juan Manuel",
    apellido: "Parada Zanotti",
    experienciaJs: false,
    experienciaVersionado: false,
    dni: 40011974,
  },
  {
    nombre: "Lucio",
    apellido: "Garcia",
    experienciaJs: false,
    experienciaVersionado: false,
    dni: 44260258,
  }
];
